/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hacker-room.glb --transform --types 
Files: public/models/hacker-room.glb [2.56MB] > /home/karun/projects/portfolio/hacker-room-transformed.glb [2.44MB] (5%)
*/

import { Mesh, MeshStandardMaterial, MeshPhysicalMaterial } from "three";
import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    screen_screens_0: Mesh;
    screen_glass_glass_0: Mesh;
    table_table_mat_0_1: Mesh;
    table_table_mat_0_2: Mesh;
    table_table_mat_0_3: Mesh;
    table_table_mat_0_4: Mesh;
    table_table_mat_0_5: Mesh;
    table_table_mat_0_6: Mesh;
    table_table_mat_0_7: Mesh;
    table_table_mat_0_8: Mesh;
    table_table_mat_0_9: Mesh;
    table_table_mat_0_10: Mesh;
    table_table_mat_0_11: Mesh;
    table_table_mat_0_12: Mesh;
  };
  materials: {
    screens: MeshStandardMaterial;
    glass: MeshPhysicalMaterial;
    table_mat: MeshStandardMaterial;
    computer_mat: MeshStandardMaterial;
    server_mat: MeshStandardMaterial;
    vhsPlayer_mat: MeshStandardMaterial;
    stand_mat: MeshStandardMaterial;
    mat_mat: MeshStandardMaterial;
    arm_mat: MeshStandardMaterial;
    tv_mat: MeshStandardMaterial;
    cables_mat: MeshStandardMaterial;
    props_mat: MeshStandardMaterial;
    ground_mat: MeshStandardMaterial;
    key_mat: MeshStandardMaterial;
  };
};

const HackerRoom = (props: React.ComponentProps<"group">) => {
  const { nodes, materials } = useGLTF(
    "/models/hacker-room.glb",
  ) as unknown as GLTFResult;

  const moniorTexture = useTexture('textures/desk/monitor.png')
  const screenTexture = useTexture('textures/desk/screen.png')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.screen_screens_0.geometry}
        material={materials.screens}
      >
        <meshMatcapMaterial map={screenTexture}/>
      </mesh>
      <mesh
        geometry={nodes.screen_glass_glass_0.geometry}
        material={materials.glass}
      />
      <mesh
        geometry={nodes.table_table_mat_0_1.geometry}
        material={materials.table_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_2.geometry}
        material={materials.computer_mat}
      >
        <meshMatcapMaterial map={moniorTexture}/>
      </mesh>
      <mesh
        geometry={nodes.table_table_mat_0_3.geometry}
        material={materials.server_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_4.geometry}
        material={materials.vhsPlayer_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_5.geometry}
        material={materials.stand_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_6.geometry}
        material={materials.mat_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_7.geometry}
        material={materials.arm_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_8.geometry}
        material={materials.tv_mat}
      >
        <meshMatcapMaterial map={moniorTexture}/>
      </mesh>
      <mesh
        geometry={nodes.table_table_mat_0_9.geometry}
        material={materials.cables_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_10.geometry}
        material={materials.props_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_11.geometry}
        material={materials.ground_mat}
      />
      <mesh
        geometry={nodes.table_table_mat_0_12.geometry}
        material={materials.key_mat}
      />
    </group>
  );
};

useGLTF.preload("/models/hacker-room.glb");
useTexture.preload('textures/desk/monitor.png');
useTexture.preload('textures/desk/screen.png');
export default HackerRoom;
