/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 react_logo.glb --transform --types 
Files: react_logo.glb [1.43MB] > /home/karun/projects/portfolio/react_logo-transformed.glb [58.92KB] (96%)
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import { Mesh, MeshStandardMaterial } from "three";
import { Float, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["React-Logo_Material002_0"]: Mesh;
  };
  materials: {
    ["Material.002"]: MeshStandardMaterial;
  };
};

const ReactLogo = (props: React.ComponentProps<"group">) => {
  const { nodes, materials } = useGLTF(
    "/models/react-logo.glb",
  ) as unknown as GLTFResult;
  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} {...props} scale={0.3} dispose={null}>
        <mesh
          geometry={nodes["React-Logo_Material002_0"].geometry}
          material={materials["Material.002"]}
          position={[0, 2.9, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/react-logo.glb");

export default ReactLogo;
