/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/target-archery.glb --transform --types 
Files: public/models/target-archery.glb [5.47MB] > /home/karun/projects/portfolio/target-archery-transformed.glb [779.12KB] (86%)
Author: Arkikon (https://sketchfab.com/ragnar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/target-archery-bafac3d3d41048fa8cd42c8d5ca81a4c
Title: Target (archery)
*/

import { Mesh, MeshStandardMaterial } from "three";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    TargetArchery_ArrowsMAT_0: Mesh;
    TargetArchery_TargetMAT_0: Mesh;
  };
  materials: {
    ArrowsMAT: MeshStandardMaterial;
    TargetMAT: MeshStandardMaterial;
  };
};

const Target = (props: React.ComponentProps<"group">) => {
  const { nodes, materials } = useGLTF(
    "/models/target-archery.glb",
  ) as unknown as GLTFResult;
  const targetRef = useRef<Mesh>(null);
  useGSAP(() => {
    if (targetRef.current) {
      gsap.to(targetRef.current?.position, {
        y: targetRef.current?.position.y + 0.5,
        duration: 1.5,
        repeat: -1,
        yoyo: true,
      });
    }
  });
  return (
    <group {...props} dispose={null} ref={targetRef} rotation={[0, Math.PI / 5, 0]}>
      <mesh
        geometry={nodes.TargetArchery_ArrowsMAT_0.geometry}
        material={materials.ArrowsMAT}
      />
      <mesh
        geometry={nodes.TargetArchery_TargetMAT_0.geometry}
        material={materials.TargetMAT}
      />
    </group>
  );
};

useGLTF.preload("/models/target-archery.glb");

export default Target;
